---
openapi: 3.0.0
info:
  title: dev-portfolio
  description: 기술 스텍 조회 API
  version: 0.1.0
servers:
- url: https://virtserver.swaggerhub.com/Modern-egile/dev-portfolio/0.1.0
  description: SwaggerHub API Auto Mocking
paths:
  /tech-stack:
    get:
      summary: Gets the teck stack image.
      parameters:
      - name: keyword
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          description: tech stack keyword
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        logoName:
          type: string
        logoUrl:
          type: string
